"use client";

import { useEffect, useMemo, useState } from "react";
import Link from "next/link";

type Task={id:string;priority:"High"|"Medium"|"Low";category:string;title:string;description:string;done:boolean};
type Audit={website?:{url?:string;hostname?:string};scores?:{overall?:number;seo?:number;technical?:number;content?:number;performance?:number;brand?:number};audit?:{title?:string;description?:string;h1?:number;h2?:number;imagesMissingAlt?:number;canonical?:boolean;robots?:boolean;sitemap?:boolean;https?:boolean};ai?:{recommendations?:Array<{priority:string;category:string;title:string;description:string}>}};

function makeTasks(a:Audit|null):Task[]{
 const r=a?.ai?.recommendations||[];
 if(r.length) return r.map((x,i)=>({id:`ai-${i}`,priority:x.priority.toLowerCase()==="high"?"High":x.priority.toLowerCase()==="low"?"Low":"Medium",category:x.category,title:x.title,description:x.description,done:false}));
 const t:Task[]=[]; const d=a?.audit;
 if(d?.title===undefined||!d.title) t.push({id:"title",priority:"High",category:"On-page",title:"Fix the page title",description:"Create a unique, keyword-focused title for the audited page.",done:false});
 if(d?.description===undefined||!d.description) t.push({id:"meta",priority:"High",category:"On-page",title:"Add a meta description",description:"Write a compelling search snippet aligned with the main keyword and intent.",done:false});
 if((d?.h1||0)!==1) t.push({id:"h1",priority:"High",category:"On-page",title:"Fix H1 structure",description:"Use one clear primary H1 that describes the page topic.",done:false});
 if((d?.imagesMissingAlt||0)>0) t.push({id:"alt",priority:"Medium",category:"Accessibility",title:"Add missing image ALT text",description:`Add descriptive ALT text to ${d?.imagesMissingAlt||0} image(s).`,done:false});
 if(d?.canonical===false) t.push({id:"canonical",priority:"High",category:"Technical",title:"Add canonical URL",description:"Set the preferred canonical URL to reduce duplicate-content ambiguity.",done:false});
 if(d?.robots===false) t.push({id:"robots",priority:"Medium",category:"Technical",title:"Add robots.txt",description:"Publish a crawlable robots.txt with the correct sitemap reference.",done:false});
 if(d?.sitemap===false) t.push({id:"sitemap",priority:"Medium",category:"Technical",title:"Create XML sitemap",description:"Generate and submit an XML sitemap containing indexable pages.",done:false});
 if(d?.https===false) t.push({id:"https",priority:"High",category:"Security",title:"Enable HTTPS",description:"Serve the site securely over HTTPS and redirect HTTP to HTTPS.",done:false});
 t.push({id:"content",priority:"Medium",category:"Content",title:"Publish keyword-focused content",description:"Create useful content around high-intent topics related to the business.",done:false});
 t.push({id:"internal",priority:"Low",category:"Internal Linking",title:"Strengthen internal links",description:"Connect related pages using descriptive anchor text and clear topic clusters.",done:false});
 return t;
}

export default function SEOGrowthPage(){
 const [audit,setAudit]=useState<Audit|null>(null); const [tasks,setTasks]=useState<Task[]>([]); const [filter,setFilter]=useState("All");
 useEffect(()=>{try{const raw=localStorage.getItem("brandpilot-latest-seo-audit");const a=raw?JSON.parse(raw):null;setAudit(a);const saved=localStorage.getItem("brandpilot-seo-growth-tasks");setTasks(saved?JSON.parse(saved):makeTasks(a));}catch{setTasks(makeTasks(null));}},[]);
 function toggle(id:string){const next=tasks.map(t=>t.id===id?{...t,done:!t.done}:t);setTasks(next);localStorage.setItem("brandpilot-seo-growth-tasks",JSON.stringify(next));}
 function reset(){const next=makeTasks(audit);setTasks(next);localStorage.setItem("brandpilot-seo-growth-tasks",JSON.stringify(next));}
 const visible=useMemo(()=>filter==="All"?tasks:tasks.filter(t=>t.priority===filter),[tasks,filter]); const completed=tasks.filter(t=>t.done).length; const progress=tasks.length?Math.round(completed/tasks.length*100):0;
 return <main className="min-h-screen bg-gradient-to-br from-black via-zinc-950 to-black px-5 py-10 text-white md:px-8 md:py-16"><div className="mx-auto max-w-7xl"><div className="flex flex-wrap items-center justify-between gap-4"><Link href="/seo-ai" className="text-sm text-blue-400 hover:text-blue-300">← SEO Audit</Link><Link href="/marketing-ai" className="rounded-full border border-white/10 px-4 py-2 text-sm text-gray-300 hover:border-blue-400/40">Marketing AI →</Link></div>
 <header className="mt-10"><p className="text-xs uppercase tracking-[0.3em] text-blue-400">SEO Growth OS</p><div className="mt-3 flex flex-col justify-between gap-6 lg:flex-row lg:items-end"><div><h1 className="text-5xl font-black tracking-tight md:text-7xl">30-Day SEO Growth Plan</h1><p className="mt-4 max-w-3xl text-lg leading-8 text-gray-400">Turn your audit into prioritized SEO actions, track progress, and move from recommendations to execution.</p>{audit?.website?.hostname&&<p className="mt-3 text-sm text-gray-500">Connected audit: <span className="text-gray-300">{audit.website.hostname}</span></p>}</div><div className="rounded-3xl border border-white/10 bg-white/[0.03] p-6 text-center"><div className="text-5xl font-black text-blue-400">{audit?.scores?.overall??"—"}</div><div className="mt-1 text-xs uppercase tracking-widest text-gray-500">SEO score</div></div></div></header>
 <section className="mt-10 grid gap-4 md:grid-cols-4"><div className="rounded-2xl border border-white/10 bg-white/[0.03] p-5"><p className="text-sm text-gray-500">Progress</p><p className="mt-2 text-3xl font-black">{progress}%</p><div className="mt-3 h-2 rounded-full bg-white/10"><div className="h-full rounded-full bg-blue-400 transition-all" style={{width:`${progress}%`}}/></div></div><div className="rounded-2xl border border-white/10 bg-white/[0.03] p-5"><p className="text-sm text-gray-500">Completed</p><p className="mt-2 text-3xl font-black">{completed}<span className="text-base text-gray-600">/{tasks.length}</span></p></div><div className="rounded-2xl border border-red-400/10 bg-red-500/5 p-5"><p className="text-sm text-gray-500">High priority</p><p className="mt-2 text-3xl font-black text-red-400">{tasks.filter(t=>t.priority==="High"&&!t.done).length}</p></div><div className="rounded-2xl border border-emerald-400/10 bg-emerald-500/5 p-5"><p className="text-sm text-gray-500">Next action</p><p className="mt-2 font-bold">{tasks.find(t=>!t.done)?.title||"All tasks complete"}</p></div></section>
 <section className="mt-8 rounded-3xl border border-white/10 bg-white/[0.03] p-6 md:p-8"><div className="flex flex-col gap-4 md:flex-row md:items-center md:justify-between"><div><p className="text-xs uppercase tracking-widest text-blue-400">Execution Board</p><h2 className="mt-2 text-2xl font-bold">SEO tasks</h2></div><div className="flex flex-wrap gap-2">{["All","High","Medium","Low"].map(x=><button key={x} onClick={()=>setFilter(x)} className={`rounded-full px-4 py-2 text-sm ${filter===x?"bg-blue-500 text-white":"border border-white/10 text-gray-400"}`}>{x}</button>)}<button onClick={reset} className="rounded-full border border-white/10 px-4 py-2 text-sm text-gray-500">Reset</button></div></div><div className="mt-6 space-y-3">{visible.length===0?<p className="rounded-2xl border border-white/10 p-6 text-gray-500">No tasks in this filter.</p>:visible.map(t=><div key={t.id} className={`rounded-2xl border p-5 transition ${t.done?"border-emerald-400/20 bg-emerald-500/5":"border-white/10 bg-black/20"}`}><div className="flex gap-4"><button onClick={()=>toggle(t.id)} aria-label={`Mark ${t.title} ${t.done?"not done":"done"}`} className={`mt-1 flex h-6 w-6 shrink-0 items-center justify-center rounded-full border ${t.done?"border-emerald-400 bg-emerald-400 text-black":"border-white/20"}`}>{t.done?"✓":""}</button><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><span className="text-xs uppercase tracking-wider text-blue-400">{t.category}</span><span className={`rounded-full px-2 py-0.5 text-[10px] font-bold uppercase ${t.priority==="High"?"bg-red-500/10 text-red-400":t.priority==="Medium"?"bg-amber-500/10 text-amber-400":"bg-emerald-500/10 text-emerald-400"}`}>{t.priority}</span></div><h3 className={`mt-2 text-lg font-bold ${t.done?"text-gray-500 line-through":""}`}>{t.title}</h3><p className="mt-1 text-sm leading-6 text-gray-500">{t.description}</p></div></div></div>)}</div></section>
 <section className="mt-8 grid gap-4 md:grid-cols-3"><div className="rounded-2xl border border-white/10 bg-white/[0.03] p-6"><p className="text-blue-400">Week 1</p><h3 className="mt-2 font-bold">Technical foundation</h3><p className="mt-2 text-sm leading-6 text-gray-500">Fix crawlability, HTTPS, canonical, robots, sitemap and critical on-page issues.</p></div><div className="rounded-2xl border border-white/10 bg-white/[0.03] p-6"><p className="text-blue-400">Week 2</p><h3 className="mt-2 font-bold">Content & keywords</h3><p className="mt-2 text-sm leading-6 text-gray-500">Build keyword clusters, landing pages, useful articles and internal links.</p></div><div className="rounded-2xl border border-white/10 bg-white/[0.03] p-6"><p className="text-blue-400">Weeks 3–4</p><h3 className="mt-2 font-bold">Growth & optimization</h3><p className="mt-2 text-sm leading-6 text-gray-500">Measure search visibility, improve weak pages, test titles and expand winning topics.</p></div></section>
 <section className="mt-8 rounded-3xl border border-blue-400/20 bg-blue-500/5 p-8 text-center"><h2 className="text-2xl font-bold">Ready to execute?</h2><p className="mt-3 text-gray-400">Use Marketing AI to turn these priorities into content, campaigns, briefs and weekly actions.</p><Link href="/marketing-ai" className="mt-6 inline-block rounded-full bg-blue-500 px-7 py-3 font-bold hover:bg-blue-600">Open Marketing AI →</Link></section>
 </div></main>;
}
