import { NextRequest, NextResponse } from "next/server";
import { createClient } from "@supabase/supabase-js";
export const runtime="nodejs";
const TIMEOUT=12000,MAX=1500000;
function supabaseServer(req:NextRequest){const url=process.env.NEXT_PUBLIC_SUPABASE_URL;const key=process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;if(!url||!key)return null;return createClient(url,key,{global:{headers:{Authorization:req.headers.get("Authorization")||""}}})}
function normalize(v:string){let u=v.trim();if(!/^https?:\/\//i.test(u))u=`https://${u}`;const p=new URL(u);if(!["http:","https:"].includes(p.protocol))throw new Error("Only HTTP and HTTPS websites are supported.");return p}
function privateHost(h:string){const x=h.toLowerCase();if(["localhost","127.0.0.1","0.0.0.0","::1","metadata","metadata.google.internal"].includes(x))return true;const m=x.match(/^(\d+)\.(\d+)\.(\d+)\.(\d+)$/);if(!m)return false;const a=+m[1],b=+m[2];return a===10||a===127||(a===172&&b>=16&&b<=31)||(a===192&&b===168)||a===169&&b===254}
async function get(u:string,timeout=TIMEOUT){const c=new AbortController(),t=setTimeout(()=>c.abort(),timeout);try{return await fetch(u,{signal:c.signal,redirect:"follow",headers:{"User-Agent":"BrandPilot-AuditBot/1.0 (+https://www.brandpilotcloud.com)",Accept:"text/html,application/xhtml+xml"}})}finally{clearTimeout(t)}}
async function html(r:Response){if(!r.body)return"";const rd=r.body.getReader(),d=new TextDecoder();let n=0,s="";while(true){const x=await rd.read();if(x.done)break;n+=x.value.byteLength;if(n>MAX){await rd.cancel();break}s+=d.decode(x.value,{stream:true})}return s+d.decode()}
function attr(h:string,name:string){const a=new RegExp(`<meta[^>]+(?:name|property)=["']${name}["'][^>]+content=["']([\\s\\S]*?)["'][^>]*>`,`i`).exec(h)||new RegExp(`<meta[^>]+content=["']([\\s\\S]*?)["'][^>]+(?:name|property)=["']${name}["'][^>]*>`,`i`).exec(h);return a?.[1]?.trim()||""}
function title(h:string){return h.match(/<title[^>]*>([\s\S]*?)<\/title>/i)?.[1]?.replace(/\s+/g," ").trim()||""}
function count(h:string,t:string){return h.match(new RegExp(`<${t}\\b`,`gi`))?.length||0}
function images(h:string){const a=h.match(/<img\b[^>]*>/gi)||[];let missing=0;for(const x of a)if(!/\balt=["'][^"']*["']/i.test(x))missing++;return{total:a.length,missing}}
function words(h:string){const x=h.replace(/<script[\s\S]*?<\/script>/gi," ").replace(/<style[\s\S]*?<\/style>/gi," ").replace(/<[^>]+>/g," ").replace(/\s+/g," ").trim();return x?x.split(/\s+/).length:0}
function links(h:string){return h.match(/<a\b[^>]*href=["'][^"']+["']/gi)?.length||0}
function score(d:any){let seo=100,content=100,technical=100,brand=100;if(!d.title)seo-=20;else if(d.title.length<30||d.title.length>60)seo-=8;if(!d.description)seo-=20;else if(d.description.length<70||d.description.length>160)seo-=8;if(d.h1===0)seo-=15;if(d.h1>1)seo-=5;if(!d.canonical)seo-=5;if(!d.robots)seo-=5;if(!d.sitemap)seo-=5;if(d.wordCount<300)content-=25;else if(d.wordCount<600)content-=12;if(!d.h1)content-=15;if(!d.h2)content-=8;if(d.links<3)content-=8;if(!d.https)technical-=25;if(!d.viewport)technical-=20;if(d.status<200||d.status>=400)technical-=25;if(!d.title)brand-=20;if(!d.description)brand-=15;if(!d.h1)brand-=15;const performance=Math.max(40,100-Math.min(35,Math.round(d.images/10)*5)-Math.min(20,Math.round(d.links/50)*5));seo=Math.max(0,seo);content=Math.max(0,content);technical=Math.max(0,technical);brand=Math.max(0,brand);return{overall:Math.round(seo*.3+performance*.2+content*.2+brand*.15+technical*.15),seo,performance,content,brand,technical}}
async function ai(audit:any,scores:any){const key=process.env.GEMINI_API_KEY;if(!key)return{summary:"Technical audit completed. Add GEMINI_API_KEY in Vercel to enable AI recommendations.",recommendations:[]};const prompt=`You are BrandPilot AI, an expert SEO auditor. Analyze ONLY this audit data and return ONLY JSON with {"summary":"2-3 sentences","recommendations":[{"priority":"high|medium|low","category":"SEO|Technical|Content|Brand|Performance","title":"short","description":"specific actionable fix"}]}. Give 5-8 evidence-based recommendations. Do not invent facts. AUDIT:${JSON.stringify({audit,scores})}`;try{const r=await fetch("https://generativelanguage.googleapis.com/v1beta/models/gemini-flash-latest:generateContent",{method:"POST",headers:{"Content-Type":"application/json","x-goog-api-key":key},body:JSON.stringify({contents:[{role:"user",parts:[{text:prompt}]}],generationConfig:{responseMimeType:"application/json"}})});if(!r.ok)return{summary:"Technical audit completed, but Gemini recommendations could not be generated.",recommendations:[]};const d=await r.json(),text=d.candidates?.[0]?.content?.parts?.map((p:any)=>p.text||"").join("")||"";return JSON.parse(text)}catch{return{summary:"Technical audit completed, but Gemini recommendations could not be generated.",recommendations:[]}}}
export async function POST(req:NextRequest){try{const body=await req.json();if(!body?.url)return NextResponse.json({error:"Website URL is required."},{status:400});const u=normalize(body.url);if(privateHost(u.hostname))return NextResponse.json({error:"Private or local websites cannot be audited."},{status:400});const r=await get(u.toString()),h=await html(r);if(!h)return NextResponse.json({error:"We could not read this website. It may block automated requests."},{status:422});const t=title(h),description=attr(h,"description"),imgs=images(h);let sitemap=false,robots=false;try{sitemap=(await get(new URL("/sitemap.xml",u).toString(),6000)).ok}catch{}try{robots=(await get(new URL("/robots.txt",u).toString(),6000)).ok}catch{}const audit={url:u.toString(),hostname:u.hostname,status:r.status,https:u.protocol==="https:",title:t,titleLength:t.length,description,descriptionLength:description.length,h1:count(h,"h1"),h2:count(h,"h2"),images:imgs.total,imagesMissingAlt:imgs.missing,links:links(h),wordCount:words(h),canonical:Boolean(h.match(/<link[^>]+rel=["']canonical["'][^>]*>/i)||h.match(/<link[^>]+href=["'][^"']+["'][^>]+rel=["']canonical["']/i)),viewport:Boolean(attr(h,"viewport")),robots,sitemap,ogTitle:attr(h,"og:title"),ogDescription:attr(h,"og:description"),ogImage:attr(h,"og:image"),twitterCard:attr(h,"twitter:card"),lang:(h.match(/<html[^>]+lang=["']([^"']+)["']/i)?.[1]||"")};const scores=score(audit),aiResult=await ai(audit,scores);let saved=null;const sb=supabaseServer(req);if(sb){const{data:{user}}=await sb.auth.getUser();if(user){const{data:customer,error:customerError}=await sb.from("customers").upsert({user_id:user.id,website_url:u.toString(),business_name:audit.hostname},{onConflict:"user_id,website_url"}).select("id,website_url,business_name").single();if(customerError)console.error("Customer save error",customerError);else{const{data:row,error:auditError}=await sb.from("seo_audits").insert({customer_id:customer.id,overall_score:scores.overall,seo_score:scores.seo,performance_score:scores.performance,content_score:scores.content,brand_score:scores.brand,technical_score:scores.technical,audit_data:audit,ai_recommendations:aiResult.recommendations||[]}).select("id,created_at").single();if(auditError)console.error("Audit save error",auditError);else saved={customerId:customer.id,auditId:row.id,createdAt:row.created_at}}}}return NextResponse.json({success:true,website:{url:u.toString(),hostname:u.hostname,status:r.status},scores,audit,ai:aiResult,saved})}catch(e){return NextResponse.json({error:e instanceof Error?e.message:"Unable to audit this website."},{status:500})}}