"use client";
import Link from "next/link";
const tools=[
 ["SEO Audit","Analyze technical SEO, content, keywords and priorities.","/ai-audit","Run Audit"],
 ["SEO Growth OS","Turn audit findings into an SEO action plan.","/seo-growth","Open SEO"],
 ["Campaign Planner","Build funnels, channels, KPIs and weekly campaigns.","/campaign-planner","Plan Campaign"],
 ["Content Studio","Create social posts, reels, blogs, email and ads.","/content-studio","Create Content"],
 ["Daily Command Center","Prioritize today's marketing execution queue.","/marketing-dashboard","Open Tasks"],
 ["Analytics & Optimization","Diagnose metrics and decide what to improve next.","/marketing-analytics","Analyze Metrics"],
];
export default function MarketingAIEmployee(){return <main className="min-h-screen bg-gradient-to-br from-black via-zinc-950 to-black px-5 py-10 text-white md:px-8 md:py-16"><div className="mx-auto max-w-7xl"><Link href="/ai-employees" className="text-sm text-blue-400">← AI Employees</Link><header className="mt-10 max-w-5xl"><p className="text-xs uppercase tracking-[0.35em] text-blue-400">BrandPilot AI Employee</p><h1 className="mt-4 text-5xl font-black tracking-tight md:text-7xl">Your AI Marketing Manager.</h1><p className="mt-5 max-w-3xl text-lg leading-8 text-gray-400">One workspace for strategy, SEO, content, campaigns, execution and optimization. Gemini helps you decide what to do next and creates the marketing assets to execute it.</p><div className="mt-7 flex flex-wrap gap-3"><Link href="/marketing-dashboard" className="rounded-xl bg-blue-500 px-5 py-3 font-bold">Open Command Center →</Link><Link href="/content-studio" className="rounded-xl border border-white/10 px-5 py-3 font-bold">Create Content</Link></div></header><section className="mt-12 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{tools.map(([name,desc,href,label],i)=><article key={name} className="group rounded-3xl border border-white/10 bg-white/[0.03] p-7 transition hover:-translate-y-1 hover:border-blue-400/30"><div className="flex items-center justify-between"><span className="text-sm font-bold text-blue-400">0{i+1}</span><span className="rounded-full border border-white/10 px-3 py-1 text-[10px] uppercase tracking-widest text-gray-500">AI</span></div><h2 className="mt-7 text-2xl font-bold">{name}</h2><p className="mt-3 min-h-14 text-sm leading-6 text-gray-500">{desc}</p><Link href={href} className="mt-6 inline-block text-sm font-bold text-white group-hover:text-blue-300">{label} →</Link></article>)}</section><section className="mt-8 rounded-3xl border border-blue-400/20 bg-blue-500/5 p-7 md:p-10"><p className="text-xs uppercase tracking-widest text-blue-400">How the employee works</p><div className="mt-6 grid gap-5 md:grid-cols-5">{[["01","Discover","Audit + data"],["02","Strategize","Goals + campaigns"],["03","Create","Assets + content"],["04","Execute","Daily priorities"],["05","Optimize","Metrics + tests"]].map(([n,t,d])=><div key={n}><span className="text-sm text-blue-400">{n}</span><h3 className="mt-2 font-bold">{t}</h3><p className="mt-1 text-xs text-gray-500">{d}</p></div>)}</div></section></div></main>}
